# Mallory Klostermann

## EDUCATION

#### **University of Illinois at Urbana-Champaign**, *expected May 2023*

###### *BSLAS in Statistics, Minor in Music*

-   Total Institution GPA: 3.93
-   Dean's List: Fall 2018, Spring 2019, Spring 2020, Fall 2020, Spring 2021, Fall 2021, Spring 2022, Fall 2022

## EXPERIENCE

#### Undergraduate Research Experience in Statistics, *January 2023 - Present*

##### Sandia National Laboratories & University of Illinois

-   Work with a team of undergraduate researchers to develop a method for forecasting lightning strikes using a generalized linear mixed effects regression model
-   Summarize completed research in a poster presentation for the Illinois Undergraduate Research Symposium


#### Independent Study, *January 2023 - Present*

##### University of Illinois, School of Social Work

-   Read peer-reviewed articles on the social work profession and how it educates students and practitioners on the criminal legal system
-   Critically examine problem-solving courts through an exploratory data analysis of the 2012 Census of Problem-Solving Courts
-   Summarize completed research in a poster presentation for the Illinois Undergraduate Research Symposium


#### Course Assistant, *January 2023 - Present*

##### STAT 385: Statistics Programming Methods, STAT 410: Statistics and Probability II
-   Facilitate personalized learning experiences in office hours to ensure student comprehension of general programming practices, data wrangling, and methods for generating data visualizations in R Studio
-   Contribute to development of meaningful student assessment methods in PrairieLearn using R and Github
-   Proctor exams and grade assignments with feedback necessary to promote future student success

#### Undergraduate Research Assistant, *January 2022 - February 2023*

##### [*Carl Bernacchi Environmental Plant Physiology Lab*](https://www.life.illinois.edu/bernacchi/), *School of Integrative Biology, USDA*

-   Analyze spreadsheets and data visualizations to generate reports of meteorological data from several field site eddy covariance flux towers to ensure proper data collection and equipment maintenance
-   Clean datasets and generate visualizations using R to locate potential errors in data collection, make corresponding corrections to the dataset, and analyze data collected by the lab Use Excel and to correctly format several years of continuously sampled data for submission to the [Ameriflux database](https://ameriflux.lbl.gov/data/aboutdata/)
-   Assist in employee training, lab maintenance, data collection, and field work at UIUC's [Energy Farm](https://energyfarm.illinois.edu/#:~:text=About%20the%20Energy%20Farm,%2DChampaign%20campus'%20South%20Farms.) and [SoyFACE](https://soyface.illinois.edu/) facilities

#### Senior Desk Clerk, *August 2021 - December 2021*

##### [*Allen Hall*](https://housing.illinois.edu/Living-Options/Residence-Halls/Undergraduate-Halls/Allen) *Front Desk, University of Illinois Housing*

-   Received training in peer supervision, leadership, and effective management in a diverse work environment
-   Trained a team of 20+ employees in customer service, daily protocol, emergency procedures, and work-related computer programs through several days of interactive presentations
-   Presented monthly meetings, coordinated scheduling, assisted in staffing, and completed managerial duties
-   Collaborated with a team of 13 paraprofessional staff to provide a cohesive, enriching living environment for more than 600 residents

**Desk Clerk**, Allen Hall Front Desk, University of Illinois Housing, *March 2019 - July 2021*

**Intern**, ToneGood Music Studio, *March 2021 - August 2021*

**Summer Counselor**, Next Generation Schools, *May 2020 - August 2020*

**Clarinet Lesson Instructor**, *February 2016 - August 2020*

**Lifeguard and Swim Instructor**, Korte Recreational Center, *May 2014 - December 2018*

## PROJECTS, VOLUNTEER WORK, & PROFESSIONAL DEVELOPMENT

#### Interdisciplinary and Critical Data Science Motivated by Social Justice, *Spring 2023*

##### [*Institute for Mathematical and Statistical Innovation*](https://www.imsi.institute/)

-   [QuantCrit and Social Justice Research Workshop](https://www.imsi.institute/activities/quantcrit-and-social-justice-research/), *10 Jan 2023*
-   [Driving the Justice Agenda Forward](https://www.imsi.institute/activities/driving-the-justice-agenda-forward/), *2 Feb 2023*

#### Statistics Tutoring, *Fall 2022*

##### [*Urbana Connections Center*](https://www.urbanaconnectionscenter.org/)

-   Assisted high school student in finding deeper conceptual understanding of course material in AP Statistics
-   Instilled learning strategies and study habits to promote improved performance across applications

#### R Shiny Applications

##### The Music of Bon Iver, Statistical Data Management, *Fall 2022*

-   Allowed user to select from and display more than 90 unique visualizations of features data pulled from the Spotify API

##### COVID Dashboard, Statistics Programming Methods, *Spring 2022*

-   Generated an interactive R Shiny Application to display COVID cases among different subgroups over time
-   Implemented reactive expressions, several R packages (ggplot2, dplyr, lubridate, etc.), and R Markdown

#### Android Application, *Spring 2022*

##### *Intro to Computer Science I*

-   Developed a basic Android application in Java that allowed users to search for restaurants in the area
-   Implemented server/client interactions, user interface components, search algorithms, JSON encoding, etc.

#### Image Mosaic, *Fall 2021*

##### *Data Science Discovery*

-   Used Python (scikit-image, NumPy) to develop an algorithm that analyzed thousands of images to generate a mosaic of a single selected image

#### [Hip Hop XPress](https://publish.illinois.edu/hiphopxpress/), *2020*

##### *University of Illinois*

-   Worked with a team of musicians, engineers, and architects to design and build a traveling music studio for middle and high school students to learn about and participate in the recording and mixing processes

## SKILLS

-   R, SAS, SQL, Python, statistical modeling and computing, machine learning algorithms, version control (Git), Jupyter notebooks
-   Problem solving, teaching, leadership, critical thinking, communication, interpersonal and presentation skills
